### ISSUE TITLE
TypeError: get_loc_key() missing 1 required positional argument: 's'

### ISSUE THREAD

**Issue by EnaldoLeite** [derkan/flask-locale#3]
Hello, 

I'm trying to fix the following error when I use _('text')

TypeError: get_loc_key() missing 1 required positional argument: 's'

https://github.com/derkan/flask-locale/blob/26b3d8a22630165d252557a39dbb6abdfaa26d19/flask_locale/__init__.py#L221

I'm using python 3.8

**Comment by derkan** [comment]
Please set `locale.localeselector` for a better language matching as in example in `README.md`
